name: dbt-oracle-adapter-test-suite
on: push

jobs:
  oracle-21_3_0-xe-test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.7, 3.8, 3.9 ]

    services:
      oracle_db_xe:
        image: container-registry.oracle.com/database/express:21.3.0-xe
        env:
          ORACLE_PWD: 8b58975df2
        ports:
          - 1521:1521

    steps:
      - name: Check out dbt-oracle repository code
        uses: actions/checkout@v3

      - name: Install Oracle Instantclient
        run: |
          chmod +x ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh
          ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh

      - name: Install dbt-oracle with core dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-dbt-adapter==0.6.0
          pip install -r requirements.txt
          pip install -e .

      - name: Run adapter tests
        run: |
          pytest tests/oracle.dbtspec tests/test_config.py
        env:
          DBT_ORACLE_USER: system
          DBT_ORACLE_HOST: localhost
          DBT_ORACLE_PORT: 1521
          DBT_ORACLE_SCHEMA: system
          DBT_ORACLE_PASSWORD: 8b58975df2
          DBT_ORACLE_DATABASE: XEPDB1
          DBT_ORACLE_SERVICE: XEPDB1
          DBT_ORACLE_PROTOCOL: tcp
          LD_LIBRARY_PATH: /opt/oracle/instantclient_21_6
          TNS_ADMIN: /opt/tns_admin

  oracle-21_3_0-xe-py36-test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.6 ]

    services:
      oracle_db_xe:
        image: container-registry.oracle.com/database/express:21.3.0-xe
        env:
          ORACLE_PWD: 8b58975df2
        ports:
          - 1521:1521

    steps:
      - name: Check out dbt-oracle repository code
        uses: actions/checkout@v3

      - name: Install Oracle Instantclient
        run: |
          chmod +x ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh
          ${{ github.workspace }}/.github/scripts/install_oracle_instantclient.sh

      - name: Install dbt-oracle with core dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-dbt-adapter==0.4.0
          pip install -r requirements.txt
          pip install -e .

      - name: Run adapter tests
        run: |
          pytest tests/oracle_py36.dbtspec tests/test_config.py
        env:
          DBT_ORACLE_USER: system
          DBT_ORACLE_HOST: localhost
          DBT_ORACLE_PORT: 1521
          DBT_ORACLE_SCHEMA: system
          DBT_ORACLE_PASSWORD: 8b58975df2
          DBT_ORACLE_DATABASE: XEPDB1
          DBT_ORACLE_SERVICE: XEPDB1
          DBT_ORACLE_PROTOCOL: tcp
          LD_LIBRARY_PATH: /opt/oracle/instantclient_21_6
          TNS_ADMIN: /opt/tns_admin





